Animation list
JQG-Ventures/2fit-webapp pull request #8
Opened 2024-10-20 22:50 UTC by GabeMByte

2024-10-22 04:35 UTC, JafetMo5601 approved these changes

2024-11-08 04:11 UTC, JafetMo5601 requested changes

2024-11-09 01:13 UTC, GabeMByte reviewed
all changes requested are done

2024-11-18 03:44 UTC, JafetMo5601 requested changes

2024-11-18 03:45 UTC, JafetMo5601 approved these changes

2026-05-26 03:13 UTC, closed without merging